@startuml
skinparam backgroundColor transparent
skinparam shadowing false
skinparam objectBorderColor #6e1423
skinparam objectBackgroundColor #faf5f5
skinparam ArrowColor #6e1423
left to right direction
title Jouer une partie — collaboration système

object "Joueur" as A
object ":Système" as S

A -[#6e1423]-> S : 1: lancerPartie()
S -[#6e1423]-> A : 2: afficherQuestion(q, temps)
A -[#6e1423]-> S : 3: soumettreRéponse(rép)
S -[#6e1423]-> A : 4: afficherRésultat(points)
S -[#6e1423]-> A : 5: afficherClassement()
S -[#6e1423]-> A : 6: afficherClassementFinal()
@enduml