@startuml
skinparam backgroundColor transparent
skinparam shadowing false
skinparam objectBorderColor #6e1423
skinparam objectBackgroundColor #faf5f5
skinparam ArrowColor #6e1423
left to right direction
title Souscrire un abonnement — collaboration système (E1 : paiement refusé)


object "Utilisateur authentifié" as A
object ":Système" as S
object "Prestataire de paiement" as P

A -[#6e1423]-> S : 1: confirmerPaiement(infos)
S -[#6e1423]-> P : 2: demanderPaiement(montant)
P -[#6e1423]-> S : 3: paiementRefusé(motif)
S -[#6e1423]-> A : 4: échecPaiement(motif)
@enduml